spring:
  datasource:
    url: jdbc:h2:mem:attackyi;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080
security:
  jwt:
    secret: change-me-please-change-me-change
    expire-hours: 12
logging:
  level:
    root: INFO
    org.springframework.security: INFO
